import Foundation
@main struct Tests {
 static func main() throws {
    let t = Date(); var s = Segmenter()
    assert(s.ingest("Hello world.",final:false,now:t).isEmpty)
    assert(s.ingest("Hello world.",final:false,now:t.addingTimeInterval(0.2)).isEmpty)
    assert(s.ingest("Hello world.",final:false,now:t.addingTimeInterval(0.7)) == ["Hello world."])
    assert(s.ingest("Hello world. How are you?",final:true) == ["How are you?"])
    assert(s.ingest("Next sentence.",final:true) == ["Next sentence."])
    var r = Segmenter()
    _ = r.ingest("The cat.",final:false,now:t)
    assert(r.ingest("The cap.",final:false,now:t.addingTimeInterval(0.6)).isEmpty)
    assert(r.ingest("The cap.",final:true) == ["The cap."])
    var c = Segmenter(); _ = c.ingest("Good morning.",final:false,now:t)
    _ = c.ingest("Good morning.",final:false,now:t.addingTimeInterval(1))
    assert(c.ingest("Good mourning.",final:true) == ["Good mourning."])
    var join = Segmenter()
    assert(join.ingest("The function changes. The",final:true) == ["The function changes."])
    assert(join.ingest("Gradient points upward.",final:true) == ["The Gradient points upward."])

    // Regression: never force a cut at 14 words, even after a hypothesis has been stable.
    var long = Segmenter()
    let clause = "So I think it is very important that everyone working on it has a well thought out theory for how their work is going to lead to"
    assert(long.ingest(clause,final:false,now:t).isEmpty)
    assert(long.ingest(clause,final:false,now:t.addingTimeInterval(5)).isEmpty)
    assert(long.ingest(clause,final:true,now:t.addingTimeInterval(5)).isEmpty)
    assert(long.ingest("a positive future.",final:true,now:t.addingTimeInterval(6)) == [clause + " a positive future."])
    var invest = Segmenter()
    assert(invest.ingest("Well",final:true,now:t).isEmpty)
    assert(invest.ingest("Well, I feel like if you're going to invest",final:true,now:t.addingTimeInterval(1)).isEmpty)
    assert(invest.ingest("So much in building AI",final:true,now:t.addingTimeInterval(2)).isEmpty)
    let investment = invest.ingest("Then it's important that people understand what your lab stands for and what your values are.",final:true,now:t.addingTimeInterval(3))
    assert(investment.count == 1 && investment[0].contains("invest So much") && !investment[0].hasPrefix("Well Well"))
    var many = Segmenter()
    assert(many.ingest("Basically AI has so many.",final:true,now:t).isEmpty)
    assert(many.flushCarry(now:t.addingTimeInterval(2.5)).isEmpty)
    assert(many.ingest("Opportunities, but there are also all these real risks.",final:true,now:t.addingTimeInterval(3)) == ["Basically AI has so many Opportunities, but there are also all these real risks."])
    var industry = Segmenter()
    let intro = "A lot of things have become conventional wisdom in the"
    assert(industry.ingest(intro,final:true,now:t).isEmpty)
    assert(industry.ingest("Industry that I just strongly disagree with.",final:true,now:t.addingTimeInterval(1)) == [intro + " Industry that I just strongly disagree with."])
    var quiet = Segmenter()
    assert(quiet.ingest("You wanted to talk about this essay",final:true,now:t).isEmpty)
    assert(quiet.preview("") == "You wanted to talk about this essay")
    assert(quiet.ingest("",final:true,now:t.addingTimeInterval(1)).isEmpty)
    assert(quiet.flushCarry(now:t.addingTimeInterval(2)).isEmpty)
    assert(quiet.ingest("Manifesto.",final:true,now:t.addingTimeInterval(2.1)) == ["You wanted to talk about this essay Manifesto."])
    assert(quiet.ingest("Trailing text without punctuation",final:true,now:t).isEmpty)
    assert(quiet.flushCarry(force:true) == ["Trailing text without punctuation"])
    var caseChange = Segmenter()
    _ = caseChange.ingest("Hello World.",final:false,now:t)
    assert(caseChange.ingest("Hello World.",final:false,now:t.addingTimeInterval(1)) == ["Hello World."])
    assert(caseChange.ingest("Hello world! How are you?",final:true) == ["How are you?"])

    var timed = Segmenter()
    assert(timed.ingest("This is an unpunctuated sentence",final:true,now:t).isEmpty)
    assert(timed.flushCarry(now:t.addingTimeInterval(2.3)) == ["This is an unpunctuated sentence"])
    assert(timed.flushCarry(now:t.addingTimeInterval(5)).isEmpty)
    var punctuation = Segmenter()
    assert(punctuation.ingest("Dr. Smith measured 3.14 units. It worked.",final:true) == ["Dr. Smith measured 3.14 units.","It worked."])
    var growth = Segmenter()
    assert(growth.ingest("The result is clear. We",final:false,now:t).isEmpty)
    assert(growth.ingest("The result is clear. We can continue",final:false,now:t.addingTimeInterval(0.7)) == ["The result is clear."])
    assert(growth.preview("The result is clear. We can continue") == "We can continue")
    assert(growth.ingest("The result is clear. We can continue.",final:true) == ["We can continue."])
    var history = CaptionHistory(); let a = UUID(), b = UUID()
    history.append(id:a,english:"First sentence",limit:300)
    history.append(id:b,english:"Second sentence",limit:300)
    history.translate(id:a,chinese:"第一句")
    assert(history.entries.count == 2 && history.entries[0].chinese == "第一句" && history.entries[1].chinese == nil)
    history.trim(to:1)
    history.translate(id:a,chinese:"Late result")
    assert(history.entries.count == 1 && history.entries[0].id == b && history.entries[0].chinese == nil)
    let root = FileManager.default.temporaryDirectory.appendingPathComponent(UUID().uuidString)
    let j = try TranscriptJournal(root:root); let seg = CaptionSegment(english:"Derivative")
    try j.record(["type":"asr_final","text":"Derivative"])
    try j.translated(seg,chinese:"导数",latency:0.25)
    let content = try String(contentsOf:j.directory.appendingPathComponent("transcript.jsonl"),encoding:.utf8)
    assert(content.split(separator:"\n").count == 2)
    let txt = try String(contentsOf:j.directory.appendingPathComponent("transcript.txt"),encoding:.utf8)
    assert(txt.contains("导数"))
    try FileManager.default.removeItem(at:root)
    print("PASS: sentence/fragment regressions, silence/stop flush, case/punctuation revisions, history and UTF-8 journal")
 }
}
