import Foundation

enum DefaultGlossary {
    static let version = 1
    static let text = """
derivative = 导数
gradient = 梯度
linear algebra = 线性代数
machine learning = 机器学习
natural language processing = 自然语言处理
language modeling = 语言建模
tokenization = 分词
subword unit = 子词单元
representation learning = 表征学习
word embedding = 词嵌入
contextual embedding = 上下文嵌入
neural machine translation = 神经机器翻译
sequence-to-sequence = 序列到序列
encoder-decoder = 编码器-解码器
self-attention = 自注意力
multi-head attention = 多头注意力
encoder-decoder attention = 编码器-解码器注意力
Transformer architecture = Transformer 架构
convolutional neural network = 卷积神经网络
residual learning = 残差学习
stochastic optimization = 随机优化
BLEU = BLEU 评分
ROUGE = ROUGE 评分
F1 score = F1 分数
pre-training = 预训练
pretraining = 预训练
post-training = 后训练
fine-tuning = 微调
finetuning = 微调
instruction following = 指令遵循
reinforcement learning = 强化学习
reinforcement learning with human feedback = 基于人类反馈的强化学习
RLHF = 基于人类反馈的强化学习
reinforcement learning with verifiable rewards = 基于可验证奖励的强化学习
RLVR = 基于可验证奖励的强化学习
direct preference optimization = 直接偏好优化
DPO = 直接偏好优化
group relative policy optimization = 组相对策略优化
GRPO = 组相对策略优化
proximal policy optimization = 近端策略优化
PPO = 近端策略优化
Constitutional AI = 宪法式 AI
experimental design = 实验设计
AI safety = AI 安全
algorithmic bias = 算法偏差
fairness = 公平性
interpretability = 可解释性
diffusion model = 扩散模型
large language model = 大语言模型
generative AI = 生成式 AI
prompt engineering = 提示词工程
prompt tuning = 提示词微调
retrieval-augmented generation = 检索增强生成
RAG = 检索增强生成
keyword search = 关键词搜索
embedding-based search = 基于嵌入的搜索
dense retrieval = 稠密检索
vector database = 向量数据库
reranking = 重排序
context construction = 上下文构建
answer generation = 答案生成
LLM benchmarking = 大语言模型基准测试
generalization = 泛化
regularization = 正则化
distributed training = 分布式训练
data parallelism = 数据并行
model parallelism = 模型并行
tensor parallelism = 张量并行
pipeline parallelism = 流水线并行
sequence parallelism = 序列并行
context parallelism = 上下文并行
expert parallelism = 专家并行
parameter server = 参数服务器
all-reduce = 全局归约
tensor core = 张量核心
NCCL = NVIDIA 集合通信库
convergence = 收敛
compute budget = 算力预算
scaling law = 缩放定律
state space model = 状态空间模型
mixture of experts = 混合专家模型
MoE = 混合专家模型
GPU disaggregation = GPU 解耦
dataflow accelerator = 数据流加速器
memory-efficient training = 内存高效训练
parameter-efficient fine-tuning = 参数高效微调
PEFT = 参数高效微调
low-rank adaptation = 低秩适配
LoRA = 低秩适配
quantized low-rank adaptation = 量化低秩适配
QLoRA = 量化低秩适配
quantization = 量化
post-training quantization = 训练后量化
weight-only quantization = 仅权重量化
KV cache = KV 缓存
KV-cache optimization = KV 缓存优化
KV-cache compression = KV 缓存压缩
continuous batching = 连续批处理
dynamic batching = 动态批处理
static batching = 静态批处理
FlashAttention = 闪速注意力
PagedAttention = 分页注意力
unified paging = 统一分页
GPU resource management = GPU 资源管理
GPU sharing = GPU 共享
GPU multiplexing = GPU 复用
inference serving = 推理服务
throughput = 吞吐量
tail latency = 尾延迟
time to first token = 首 token 延迟
time to target quality = 达到目标质量的时间
memory footprint = 内存占用
model FLOP utilization = 模型 FLOP 利用率
MFU = 模型 FLOP 利用率
service-level objective = 服务级别目标
SLO = 服务级别目标
prefill = 预填充
disaggregated prefill and decode = 预填充与解码解耦
prefix caching = 前缀缓存
speculative decoding = 推测式解码
multi-tenancy = 多租户
pruning = 剪枝
sparsity = 稀疏性
knowledge distillation = 知识蒸馏
activation checkpointing = 激活检查点
distributed checkpointing = 分布式检查点
performance engineering = 性能工程
profiling = 性能分析
reproducible benchmarking = 可复现基准测试
bottleneck analysis = 瓶颈分析
Amdahl's law = 阿姆达尔定律
roofline model = 屋顶线模型
kernel optimization = 内核优化
memory hierarchy = 存储层次结构
agentic AI = 智能体 AI
tool-assisted LLM = 工具辅助大语言模型
tool calling = 工具调用
function calling = 函数调用
multi-agent system = 多智能体系统
Model Context Protocol = 模型上下文协议
MCP = 模型上下文协议
voice AI agent = 语音 AI 智能体
speech-to-text = 语音转文字
STT = 语音转文字
text-to-speech = 文字转语音
TTS = 文字转语音
multimodal machine learning = 多模态机器学习
vision-language model = 视觉语言模型
large multimodal model = 大型多模态模型
agent architecture = 智能体架构
reactive agent = 反应式智能体
plan-execute architecture = 规划-执行架构
supervisor-worker architecture = 监督者-工作者架构
feedback loop = 反馈循环
dynamic workflow = 动态工作流
conditional routing = 条件路由
state machine = 状态机
action representation = 动作表示
tool signature = 工具签名
API contract = API 契约
schema validation = 模式验证
serialization = 序列化
local dispatch = 本地调度
remote procedure call = 远程过程调用
RPC = 远程过程调用
dependency DAG = 依赖有向无环图
topological order = 拓扑顺序
bounded concurrency = 有界并发
fork-join = 分叉-合并
critical path = 关键路径
context working set = 上下文工作集
lossy summarization = 有损摘要
context compaction = 上下文压缩
provenance = 溯源信息
source versioning = 源版本管理
workflow state = 工作流状态
durable state = 持久化状态
checkpoint boundary = 检查点边界
run identity = 运行标识
resumption = 恢复执行
desired state = 期望状态
observed state = 观测状态
reconciliation = 调和
service discovery = 服务发现
readiness probe = 就绪探针
liveness probe = 存活探针
ephemeral storage = 临时存储
persistent storage = 持久存储
partial failure = 局部故障
retry amplification = 重试放大
exponential backoff = 指数退避
idempotency = 幂等性
exactly-once semantics = 精确一次语义
observability = 可观测性
end-to-end latency = 端到端延迟
four golden signals = 四大黄金信号
saturation = 饱和度
recovery time = 恢复时间
token budget = token 预算
admission control = 准入控制
usage accounting = 用量核算
"""

    static func merging(into existing: String) -> String {
        let existingKeys = Set(existing.split(separator:"\n").compactMap { line -> String? in
            let parts = line.split(separator:"=",maxSplits:1)
            guard let key = parts.first?.trimmingCharacters(in:.whitespacesAndNewlines), !key.isEmpty else { return nil }
            return key.lowercased()
        })
        let additions = text.split(separator:"\n").filter { line in
            guard let key = line.split(separator:"=",maxSplits:1).first?.trimmingCharacters(in:.whitespacesAndNewlines) else { return false }
            return !existingKeys.contains(key.lowercased())
        }
        guard !additions.isEmpty else { return existing }
        return existing.trimmingCharacters(in:.whitespacesAndNewlines) + "\n" + additions.joined(separator:"\n")
    }
}
